jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    # Add additional steps to install dependencies
    - name: Run Streamlit App
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: streamlit run your_app.py
