name: Deploy AI Voice Assistant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Add any steps required to set up your environment here

    - name: Create .env file
      run: |
        echo OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} > .env
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Streamlit App
      run: streamlit run your_app.py
