jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    # Add steps to install dependencies here
    - name: Create .env file
      run: |
        echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Streamlit App
      run: streamlit run your_app.py
